---
title: "FBA_final"
author: "Ji-eun Park"
date: "4/11/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)

```

Code for linear model for Asthma symptoms
---
title: "FBA_final"
author: "Ji-eun Park"
date: "4/11/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)

```

Code for linear model for Asthma symptoms

```{r}
ASU <- read.csv("/Users/jieun/Desktop/FBA/final/data/csv/ASU.csv")

ASU <- ASU %>%
  select(Sub.Org.Accession, group,event, ASU_q1,ASU_q2,ASU_q3,ASU_q7a1)

ASU$ASU_q7a1 <- ifelse(ASU$ASU_q7a1==".",NA,as.numeric(as.character(ASU$ASU_q7a1)))

names <- c("ID","treatment","visit","wheeze","slowact","insomnia","missedschool")

colnames(ASU) <- names


library(car)


library(ggplot2)
n_symp <- ASU %>%
  select(ID,treatment,visit,wheeze,slowact,insomnia,missedschool) %>%
  group_by(visit,treatment) %>%
  summarise(avg_wheeze=round(mean(wheeze,na.rm=T),2),sd_wheeze=round(sd(wheeze,na.rm=T),2),avg_slowact=round(mean(slowact,na.rm=T),2),sd_slowact=round(sd(slowact,na.rm=T),2),avg_insomnia=round(mean(insomnia,na.rm=T),2),sd_insomnia=round(sd(insomnia,na.rm=T),2),avg_schoolmiss=round(mean(missedschool,na.rm=T),2),sd_schoolmiss=round(sd(missedschool,na.rm=T),2))

ggplot(data=n_symp,aes(x=visit,y=avg_wheeze,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
  labs(title="Average Wheeze symptom days",x="visits",y="symptom days")



ggplot(data=n_symp,aes(x=visit,y=avg_slowact,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
  labs(title="Average Days of activity interference",x="visits",y="Days of activity interference")




ggplot(data=n_symp,aes(x=visit,y=avg_insomnia,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
    labs(title="Average Nights of sleep disruption",x="visits",y="Nights of sleep disruption")


ggplot(data=n_symp,aes(x=visit,y=avg_schoolmiss,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
    labs(title="Average School days missed",x="visits",y="School days missed")



```

Maximum symptom linear

```{r}
n_max <- ASU %>%
  group_by(ID,visit) %>%
  summarise(treatment=treatment,maxday = max(wheeze,slowact,insomnia,missedschool,na.rm=T)) 

nmax <- ASU %>%
  group_by(ID,visit) %>%
  summarise(treatment=treatment,maxday = max(wheeze,slowact,insomnia,missedschool,na.rm=T)) %>%
  group_by(treatment,visit) %>%
  summarise(avg_max=mean(maxday))


ggplot(data=nmax,aes(x=visit,y=avg_max,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
    labs(title="Average Maximum Symptom days",x="visits",y="Maximum Symptom days")
```

```{r}
ENO <- read.csv("/Users/jieun/Desktop/FBA/final/data/csv/ENO.csv")

ENO <- ENO %>%
  select(Sub.Org.Accession, group, event, ENO_q19)

ENO$ENO_q19 <- ifelse(ENO$ENO_q19==".",NA,as.numeric(as.character(ENO$ENO_q19)))

names <- c("ID","treatment","visit","avg_FENO")
colnames(ENO) <- names


avg_feno <- ENO %>%
  group_by(ID,visit) %>%
  summarise(treatment=treatment,avgFENO = mean(avg_FENO,na.rm=T)) %>%
  group_by(treatment,visit) %>%
  summarise(avgENO=mean(avgFENO,na.rm=T))

ggplot(data=avg_feno,aes(x=visit,y=avgENO,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
    labs(title="Exhaled Nitric Oxide",x="visits",y="Geometrix mean FeNO(ppb)")
```

```{r}
act <- ACT %>%
  select(ID,Treatment,Visit,ACT_q1,ACT_q2,ACT_q3,ACT_q4,ACT_q5) %>%
  group_by(Treatment,ID,Visit) %>% summarise(sum=sum(ACT_q1,ACT_q2,ACT_q3,ACT_q4,ACT_q5,na.rm=T)) %>%
  arrange(ID)

ACT %>%
  select(ID,Treatment,Visit,ACT_q1,ACT_q2,ACT_q3,ACT_q4,ACT_q5) %>%
  group_by(Treatment,ID,Visit) %>% summarise(sum=sum(ACT_q1,ACT_q2,ACT_q3,ACT_q4,ACT_q5,na.rm=T)) %>%
  arrange(ID) %>%
  group_by(Treatment) %>%
  summarise(mean(sum))

```

```{r}
fit_wheeze <- lm(wheeze~treatment+visit,data=ASU)
anova(fit_wheeze)

fit_slowact <- lm(slowact~treatment+visit,data=ASU)
anova(fit_slowact)

fit_insomnia <- lm(insomnia~treatment+visit,data=ASU)
anova(fit_insomnia)

fit_missedschool <- lm(missedschool~treatment+visit,data=ASU)
anova(fit_missedschool)

fit_max <- lm(maxday~treatment+visit,data=n_max)
anova(fit_max)

fit_act <- lm(sum ~ Treatment + Visit,data=act)
anova(fit_act)

```

```{r}
# linear model
ST <- read.csv("/Users/jieun/Desktop/FBA/final/data/csv/ST.csv")

ST <- ST %>%
  select(Sub.Org.Accession, group, event, ST_q7c, ST_q7d)

ST$ST_q7c <- ifelse(ST$ST_q7c==".",NA,as.numeric(as.character(ST$ST_q7c)))
ST$ST_q7d <- ifelse(ST$ST_q7d==".",NA,as.numeric(as.character(ST$ST_q7d)))

names(ST) <- c("ID","treatment","visit","FEVperc_mean_v1","FEVFVC_mean_v1")
ST <- ST[-1688,]
ST <- ST[-which(ST$visit=="AceMech Repeat Visit"),]

fit1 <- lm(FEVperc_mean_v1 ~ treatment, data = ST)
fit1.2 <- lm(FEVperc_mean_v1 ~ treatment+visit, data = ST)

fit2 <- lm(FEVFVC_mean_v1 ~ treatment, data = ST)
fit2.2 <- lm(FEVFVC_mean_v1 ~ treatment+visit, data = ST)
  
summary(fit1)
summary(fit1.2)

summary(fit2)
summary(fit2.2)

anova(fit1)
anova(fit1.2)

# table of result
dfp <- function(p.val){
  format.pval(pv = p.val, eps = 0.001, nsmall = 3)
}


```

```{r}
install.packages("blockrand")
library(blockrand)
s1 <- blockrand(54, stratum = "site1", block.sizes = 10)
s1
s2 <- blockrand(55, num.levels = 2, levels = LETTERS[seq(length = 2)],
    id.prefix="site1", block.sizes = 10, block.prefix="site1", uneq.min=0, uneq.maxit=10)

s3 <- blockrand(55, num.levels = 2, levels = LETTERS[seq(length = 2)],
    id.prefix="site1", block.sizes = 10, block.prefix="site1", uneq.min=0, uneq.maxit=10)

s4 <- blockrand(55, num.levels = 2, levels = LETTERS[seq(length = 2)],
    id.prefix="site1", block.sizes = 10, block.prefix="site1", uneq.min=0, uneq.maxit=10)

```


```{r}
SPE <- read.csv("/Users/jieun/Desktop/FBA/final/data/csv/SPE.csv")

var <- names(SPE) %in% c("Sub.Org.Accession","event" ,"group","SPE_q8d","SPE_q9") 

SPE <- SPE[var]
SPE$SPE_q8d <- as.numeric(as.character(SPE$SPE_q8d))
SPE$SPE_q9 <- as.numeric(as.character(SPE$SPE_q9))
BMI <- SPE %>%
  select(Sub.Org.Accession,SPE_q8d,SPE_q9) %>%
  group_by(Sub.Org.Accession) %>%
  summarise(BMI=(SPE_q9/(SPE_q8d/100)^2))

obese <- BMI %>%
  filter(BMI>=31) %>%
  select(Sub.Org.Accession)

```




Table for Linear Model
```{r}
# linear model
ST <- read.csv("/Users/xuchenghuiyun/Desktop/FBA/Final Project/datas/ST.csv")

ST <- ST %>%
  select(group, event, ST_q7c, ST_q7d)

ST$ST_q7c <- ifelse(ST$ST_q7c==".",NA,as.numeric(as.character(ST$ST_q7c)))
ST$ST_q7d <- ifelse(ST$ST_q7d==".",NA,as.numeric(as.character(ST$ST_q7d)))

names(ST) <- c("treatment","visit","FEVperc_mean_v1","FEVFVC_mean_v1")
ST <- ST[-which(ST$visit=="Unscheduled Visit"),]
ST <- ST[-which(ST$visit=="AceMech Repeat Visit"),]

#fit1 <- lm(FEVperc_mean_v1 ~ treatment, data = ST)
fit_FEVperc <- lm(FEVperc_mean_v1 ~ treatment+visit, data = ST)

#fit2 <- lm(FEVFVC_mean_v1 ~ treatment, data = ST)
fit_FEVFVC <- lm(FEVFVC_mean_v1 ~ treatment+visit, data = ST)
  
#summary(fit1)
summary(fit_FEVperc)

#summary(fit2)
summary(fit_FEVFVC)

anova(fit_FEVperc)
anova(fit_FEVFVC)


# table of result
dfp <- function(p.val){
  format.pval(pv = p.val, eps = 0.001, nsmall = 3)
}

library(car)
# wheeze
fit_wheeze <- lm(wheeze~treatment+visit,data=ASU)
anova(fit_wheeze)

# slowact
fit_slowact <- lm(slowact~treatment+visit,data=ASU)
anova(fit_slowact)

# insomnia
fit_insomnia <- lm(insomnia~treatment+visit,data=ASU)
anova(fit_insomnia)

# missschool
fit_missedschool <- lm(missedschool~treatment+visit,data=ASU)
anova(fit_missedschool)

# Maximum symptom
n_max <- ASU %>%
  group_by(ID,visit) %>%
  summarise(treatment=treatment,maxday = max(wheeze,slowact,insomnia,missedschool,na.rm=T))

fit_max <- lm(maxday~treatment+visit,data=n_max)
anova(fit_max)


# ENO
ENO <- read.csv("/Users/xuchenghuiyun/Desktop/FBA/Final Project/datas/ENO.csv")

ENO <- ENO %>%
  select(Sub.Org.Accession, group, event, ENO_q19)

ENO$ENO_q19 <- ifelse(ENO$ENO_q19==".",NA,as.numeric(as.character(ENO$ENO_q19)))

names <- c("ID","treatment","visit","avg_FENO")
colnames(ENO) <- names

fit_eno <- lm(avg_FENO~treatment+visit,data=ENO)
anova(fit_eno)


act <- ACT %>%
  select(ID,Treatment,Visit,ACT_q1,ACT_q2,ACT_q3,ACT_q4,ACT_q5) %>%
  group_by(Treatment,ID,Visit) %>% summarise(sum=sum(ACT_q1,ACT_q2,ACT_q3,ACT_q4,ACT_q5,na.rm=T)) %>%
  arrange(ID)
fit_act <- lm(sum ~ Treatment + Visit,data=act)
anova(fit_act)

a <- dfp(anova(fit_max)$'Pr(>F)'[1])
p <- dfp(summary(fit_max)$coef[2, 4])
e <- round(summary(fit_max)$coef[2, 1],3)
x1 <- as.data.frame(cbind(e, p, a))

a <- dfp(anova(fit_wheeze)$'Pr(>F)'[1])
p <- dfp(summary(fit_wheeze)$coef[2, 4])
e <- round(summary(fit_wheeze)$coef[2, 1],3)
x2 <- as.data.frame(rbind(x1,cbind(e, p, a)))

a <- dfp(anova(fit_slowact)$'Pr(>F)'[1])
p <- dfp(summary(fit_slowact)$coef[2, 4])
e <- round(summary(fit_slowact)$coef[2, 1],3)
x3 <- as.data.frame(rbind(x2,cbind(e, p, a)))

a <- dfp(anova(fit_insomnia)$'Pr(>F)'[1])
p <- dfp(summary(fit_insomnia)$coef[2, 4])
e <- round(summary(fit_insomnia)$coef[2, 1],3)
x4 <- as.data.frame(rbind(x3,cbind(e, p, a)))

a <- dfp(anova(fit_missedschool)$'Pr(>F)'[1])
p <- dfp(summary(fit_missedschool)$coef[2, 4])
e <- round(summary(fit_missedschool)$coef[2, 1],3)
x5 <- as.data.frame(rbind(x4,cbind(e, p, a)))

a <- dfp(anova(fit_FEVperc)$'Pr(>F)'[1])
p <- dfp(summary(fit_FEVperc)$coef[2, 4])
e <- round(summary(fit_FEVperc)$coef[2, 1],3)
x6 <- as.data.frame(rbind(x5,cbind(e, p, a)))

a <- dfp(anova(fit_FEVFVC)$'Pr(>F)'[1])
p <- dfp(summary(fit_FEVFVC)$coef[2, 4])
e <- round(summary(fit_FEVFVC)$coef[2, 1],3)
x7 <- as.data.frame(rbind(x6,cbind(e, p, a)))

a <- dfp(anova(fit_act)$'Pr(>F)'[1])
p <- dfp(summary(fit_act)$coef[2, 4])
e <- round(summary(fit_act)$coef[2, 1],3)
x8 <- as.data.frame(rbind(x7,cbind(e, p, a)))

colnames(x8) <- c("Estimate", "p.t.test", "p.anova")
rownames(x8) <- c("Max Symptom","Days of Wheeze","Days of activity interference","Nights of sleep disruption","School days missed","FEV%","FEV/FVC","ACTscore")
knitr::kable(x8)


# plot
lf <- ST %>%
  group_by(treatment, visit) %>%
  summarise(mu1=mean(FEVperc_mean_v1, na.rm = T), mu2=mean(FEVFVC_mean_v1, na.rm = T))


ggplot(data=lf,aes(x=visit,y=mu1,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
    labs(title="Lung Function",x="visits",y="Average FEV1 Percentage")

ggplot(data=lf,aes(x=visit,y=mu2,group=treatment,color=treatment)) +
  geom_line(stat="identity",position="identity") +
    labs(title="Lung Function",x="visits",y="Average FEV1/FVC")

```

